apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-reconciler
  namespace: app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: app
  name: app-role
rules:
- apiGroups:
  - ""
  resources: 
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources: 
  - pods
  - configmaps
  - services
  - endpoints
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - statefulsets
  - replicasets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - "source.toolkit.fluxcd.io"
  resources: 
  - helmrepositories
  resourceNames:
  - bitnami
  verbs:
  - get
- apiGroups:
  - "helm.toolkit.fluxcd.io"
  resources:
  - helmreleases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-role-binding
  namespace: app
subjects:
- kind: ServiceAccount
  name: app-reconciler
  namespace: app
roleRef:
  kind: Role
  name: app-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: helm
  name: app-role
rules:
- apiGroups:
  - ""
  resources: 
  - secrets
  verbs:
  - get
  - list
  - create
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-role-binding
  namespace: helm-storage
subjects:
- kind: ServiceAccount
  name: app-reconciler
  namespace: app
roleRef:
  kind: Role
  name: app-role
  apiGroup: rbac.authorization.k8s.io  